on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3

      - name: Run test suite
        run: |
          pipenv run test -

      - name: Run flake8
        run: |
          pipenv run flake8 .

      - name: Run mypy
        run: |
          pipenv run mypy .

      - name: Run isort
        run: |
          pipenv run isort . --profile=black --line-length=79

      - name: commit isort changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git diff-index --cached --quiet HEAD || git commit -m "apply isort format change"

      - name: push isort changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.AUTOCOMMIT_TOKEN }}
          branch: ${{ github.ref }}
